// Generated by CoffeeScript 1.9.3
var compactObj, mapObj, mapObjKey, pairs, toObj;

pairs = function(o) {
  var a_, k, v;
  a_ = [];
  for (k in o) {
    v = o[k];
    a_.push([k, v]);
  }
  return a_;
};

toObj = function(a) {
  var i, k, len, o_, ref, v;
  o_ = {};
  for (i = 0, len = a.length; i < len; i++) {
    ref = a[i], k = ref[0], v = ref[1];
    o_[k] = v;
  }
  return o_;
};

mapObj = function(o, f) {
  var k, o_, v;
  o_ = {};
  for (k in o) {
    v = o[k];
    o_[k] = f(o[k]);
  }
  return o_;
};

mapObjKey = function(o, f) {
  var k, o_, v;
  o_ = {};
  for (k in o) {
    v = o[k];
    o_[k] = f(k);
  }
  return o_;
};

compactObj = function(o) {
  var k, o_, v;
  o_ = {};
  for (k in o) {
    v = o[k];
    if (v != null) {
      o_[k] = v;
    }
  }
  return o_;
};

module.exports = {
  pairs: pairs,
  toObj: toObj,
  mapObj: mapObj,
  mapObjKey: mapObjKey,
  compactObj: compactObj
};
