// Generated by CoffeeScript 1.9.3
var React, ValidatedField, ValidatedFormMixin, helpers, validation;

React = require('react');

helpers = require('./helpers');

validation = require('./validation');

ValidatedFormMixin = {
  validate: function() {
    return helpers.compactObj(helpers.mapObjKey(this.fields, (function(_this) {
      return function(field_name) {
        return _this.refs[field_name].validate();
      };
    })(this)));
  },
  values: function() {
    return helpers.mapObjKey(this.fields, (function(_this) {
      return function(field_name) {
        return _this.refs[field_name].value();
      };
    })(this));
  },
  trySubmit: function(e) {
    var errors, values;
    e.preventDefault();
    if (!this.state.loading) {
      this.setState({
        errors: {}
      });
      errors = this.validate();
      if (Object.keys(errors).length > 0) {
        return this.setState({
          errors: errors
        });
      } else {
        values = this.values();
        return this.onSubmit(values);
      }
    }
  },
  onChange: function(key) {
    return (function(_this) {
      return function(value) {
        var values;
        values = _this.state.values || {};
        values[key] = value;
        return _this.setState({
          values: values
        }, function() {
          return typeof _this.onChanged === "function" ? _this.onChanged(key, value) : void 0;
        });
      };
    })(this);
  },
  clear: function() {
    return this.setState({
      values: {},
      errors: {}
    });
  },
  renderField: function(field_name) {
    var field, ref, ref1;
    field = this.fields[field_name];
    return React.createElement(ValidatedField, React.__spread({}, field, {
      "ref": field_name,
      "key": field_name,
      "name": field_name,
      "value": (ref = this.state.values) != null ? ref[field_name] : void 0,
      "error": (ref1 = this.state.errors) != null ? ref1[field_name] : void 0,
      "onChange": this.onChange(field_name)
    }));
  }
};

ValidatedField = React.createClass({displayName: "ValidatedField",
  getDefaultProps: function() {
    return {
      type: 'text'
    };
  },
  value: function() {
    return this.props.value;
  },
  validate: function() {
    var validator;
    if (this.props.optional) {
      return null;
    }
    validator = this.props.validator || validation[this.props.type] || validation.exists;
    if (!validator(this.props.value)) {
      return this.props.error_message || ("Nothing in " + this.props.name);
    }
    return null;
  },
  changeValue: function(e) {
    var value;
    value = e.target.value;
    return this.props.onChange(value);
  },
  render: function() {
    var field_class;
    field_class = 'field';
    if (this.props.error) {
      field_class += ' has-error';
    }
    return React.createElement("div", {
      "className": field_class
    }, React.createElement("input", {
      "key": this.props.name,
      "name": this.props.name,
      "type": this.props.type,
      "placeholder": this.props.placeholder || this.props.name,
      "value": this.props.value,
      "onChange": this.changeValue
    }), (this.props.error ? React.createElement("span", {
      "className": 'error'
    }, this.props.error) : void 0));
  }
});

module.exports = {
  ValidatedField: ValidatedField,
  ValidatedFormMixin: ValidatedFormMixin
};
