// Generated by CoffeeScript 1.10.0
var exists, has_length, valid_email, valid_password, valid_phone;

exists = function(value) {
  if (value == null) {
    return false;
  }
  if (typeof value === 'string') {
    return has_length(value);
  } else {
    return true;
  }
};

has_length = function(value) {
  return value.length > 0;
};

valid_password = function(value) {
  return value.length >= 4;
};

valid_phone = function(value) {
  var phone_regexp;
  phone_regexp = RegExp('^\\(?[0-9]{3}-?[0-9]{3}-?[0-9]{4}$', 'i');
  return value.match(phone_regexp);
};

valid_email = function(value) {
  var email_regexp;
  email_regexp = RegExp('^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}$', 'i');
  return value.match(email_regexp);
};

module.exports = {
  exists: exists,
  has_length: has_length,
  valid_password: valid_password,
  valid_phone: valid_phone,
  valid_email: valid_email
};
